image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: test
        services:
          - docker
        script:
          - docker build -t openid.net/tests-oidc4ida tests
          - docker run -v `pwd`:/data openid.net/tests-oidc4ida
    - step:
        name: build
        services:
          - docker
        script:
          - docker run -v `pwd`:/data danielfett/markdown2rfc openid-connect-4-identity-assurance.md
          - docker run -v `pwd`:/data danielfett/markdown2rfc openid-connect-authority.md
          - mv openid-connect-4-identity-assurance-*.html openid-connect-4-identity-assurance.html
          - mv openid-authority-*.html openid-authority.html
        artifacts:
          - openid-connect-4-identity-assurance.html
          - openid-authority.html
  branches:
    master:
      - step:
          name: test
          services:
            - docker
          script:
            - docker build -t openid.net/tests-oidc4ida tests
            - docker run -v `pwd`:/data openid.net/tests-oidc4ida
      - step:
          name: build
          services:
            - docker
          script:
            - docker run -v `pwd`:/data danielfett/markdown2rfc openid-connect-4-identity-assurance.md
            - docker run -v `pwd`:/data danielfett/markdown2rfc openid-connect-authority.md
            - mv openid-connect-4-identity-assurance-*.html openid-connect-4-identity-assurance.html
            - mv openid-authority-*.html openid-authority.html
          artifacts:
            - openid-connect-4-identity-assurance.html
            - openid-authority.html
      - step:
          name: publish
          script:
            - git config --global user.email "pipeline@bitbucket.org"
            - git config --global user.name "Bitbucket eKYC Pipeline"
            - git config --global push.default simple
            - git clone git@bitbucket.org:openid/openid.bitbucket.io.git
            - mkdir -p openid.bitbucket.io/ekyc/
            - cp openid-connect-4-identity-assurance.html openid-authority.html openid.bitbucket.io/ekyc/
            - cd openid.bitbucket.io/ekyc
            - git add *
            - git commit -m "Update eKYC drafts"
            - git push origin master
